### ISSUE TITLE
How do I get a quaternion or rotation matrix out of PSMoveServiceEX?

### ISSUE THREAD

**Issue by TheGeek007** [Timocop/PSMoveServiceEx#10]
I've got a project I'm working on that involves PSMoves paired with PS Navi's, connected with PSMoveServiceEX, then PSMoveFreePIEBridge gives me output to FreePIE, then I use FreePIE's Razer Hydra drivers to plug into SteamVR. Everything works, except for the roll value from PSMoveServiceEX. It varies from 90/-90, and it "rolls over" when it goes past 90 degrees. I'm unsure how to handle this in my project.

What kind of rotation data is being output by PSMoveServiceEX? Tait-Bryan angles, or Euler angles?

Is there any way to get a rotation quaternion or rotation matrix out of PSMoveServiceEX?

Do you have any advice for trying to pass rotation data to SteamVR?

I tried looking at PSMoveSteamVRBridge, but I couldn't make heads or tails of it. And it looks like its using quaternions and rotation matrixes' rather than angles.

My apologies for questions rather than a true issue or bug.

**Comment by Timocop** [comment]
Its using quaternion for controller orientation in CAPI
https://github.com/Timocop/PSMoveServiceEx/blob/master-experimental/src/psmoveclient/PSMoveClient_CAPI.cpp#L618

**Comment by TheGeek007** [comment]
Thanks for the info!

I'm considering creating a plugin for FreePIE to read PSMoveService outputs, as PSMoveFreePIEBridge only does rotations.

Without writing the code for me, can you give me any guidance for getting a quaternion out of PSMoveServiceEX for up to 3 controllers? Is this possible with PSMoveServiceEX?

**Comment by TheGeek007** [comment]
I'm closing this issue as the problem is not with PSMoveService, but with PSMoveFreePIEBridge. Now if I only knew how to build from code...

**Comment by Timocop** [comment]
You can lookup PSMoveService Tool in the repo to see how its getting the controller orientation. You can also look in the test source code as well.
https://github.com/Timocop/PSMoveServiceEx/blob/master-experimental/src/tests/test_console_CAPI.cpp
