### ISSUE TITLE
PSMoveServiceEx gets stuck on "Connecting to PSMoveService" in config tool

### ISSUE THREAD

**Issue by CannedToes** [Timocop/PSMoveServiceEx#12]
Every single time I try to connect to PSMoveServiceAdmin through PSMoveConfigTool, it gets stuck on "Connecting to PSMoveService"
logs look pretty normal? (btw i have used the original version of PSMoveService on this computer before)

[2022-07-30 17:13:21.848]: main - Starting PSMoveService v0.16.1.0 (protocol v0.9-alpha 9.0.0)
[2022-07-30 17:13:21.858]: USBAsyncRequestManager::startup - Requested LibUSBApi
[2022-07-30 17:13:21.859]: USBAsyncRequestManager::startup - Creating LibUSBApi
[2022-07-30 17:13:21.863]: USBAsyncRequestManager::startup - Initialized USB API
[2022-07-30 17:13:21.866]: DeviceManager::startup - Platform Hotplug API is ENABLED
[2022-07-30 17:13:21.948]: bluetooth_get_host_address - Found a bluetooth radio
[2022-07-30 17:13:21.949]: bluetooth_get_host_address - Retrieved radio info
[2022-07-30 17:13:21.957]: PSMoveService - ------------------------------------------
[2022-07-30 17:13:21.958]: PSMoveService - Startup successful! Entering main loop...
[2022-07-30 17:13:21.960]: PSMoveService - ------------------------------------------

**Comment by Timocop** [comment]
Can you take a screenshot of the console window. Some of the verbose infos are only displayed in the console window.

**Comment by CannedToes** [comment]
Sure! Here you go,
https://imgur.com/a/39YnLuo

**Comment by Timocop** [comment]
What kind of controllers do you have attached to your computer?

**Comment by CannedToes** [comment]
I have the PSMoveControllers Attached?

**Comment by Timocop** [comment]
Which types of controllers. PS3 Gen1, PS3 Gen2 or PS4?

**Comment by CannedToes** [comment]
I checked the model number and it says "CECH-ZCM1E" which I think are PS3
Gen1 but I also have the "CECH-ZCM2" which are the PS4 Ones that give me
the same error, thanks again!

**Comment by Timocop** [comment]
PS3 Gen1 (CECH-ZCM1E) starts with a serial number `G` or `0 - 2`
PS3 Gen2 (CECH-ZCM1E) starts higher than 2
PS4 (CECH-ZCM2)
Can you remove (via "Devices and Printers" > "Motion Controller") all controllers and only pair the PS3 Gen1?

**Comment by Cantoooo** [comment]
Hello again!
Once I disconnected all my controllers I could startup PSMoveServiceEX and access the config tool but as soon as I plugged in my PS3MoveController the program became unresponsive and it wouldn't show that there was a controller connected for pairing, and when I tried to go back to the settings list then go back into controller settings then it just gets stuck on "Getting Controller List Response"

I have attached all the photos of the command line
![Desktop Screenshot 2022 07 31 - 21 52 15 93](https://user-images.githubusercontent.com/88938534/182043008-2f7d85a4-304b-4304-a028-e167deb07263.png)
![Desktop Screenshot 2022 07 31 - 21 52 22 34](https://user-images.githubusercontent.com/88938534/182043009-c472dec4-fc36-44ad-90da-8840b939b408.png)
![Desktop Screenshot 2022 07 31 - 21 01 55 55](https://user-images.githubusercontent.com/88938534/182042998-5beb6a97-79d8-4926-bc67-8982e0e47e21.png)
![Desktop Screenshot 2022 07 31 - 21 52 10 34](https://user-images.githubusercontent.com/88938534/182043001-3aff58b2-5735-4df4-bf69-60364d839f18.png)

**Comment by CannedToes** [comment]
Hello again!

After disconnecting all the controllers, I got to access the config tool, but after trying to plugin my PS3 Gen1 Controller the program becomes unresponsive, I tried going out of it then going back in but it just then gets stuck on "Getting Controller List Response"

I have attached photos of the problem
![Desktop Screenshot 2022 07 31 - 21 52 10 34](https://user-images.githubusercontent.com/88938534/182043095-9a3a0b38-0540-4be1-a517-a199e39b2635.png)
![Desktop Screenshot 2022 07 31 - 21 52 15 93](https://user-images.githubusercontent.com/88938534/182043099-518645f0-a9a3-41f7-a627-826b022416d4.png)
![Desktop Screenshot 2022 07 31 - 21 52 22 34](https://user-images.githubusercontent.com/88938534/182043105-32dc47c5-8733-4113-b2e5-8617433d751b.png)

**Comment by Timocop** [comment]
This seems like one of those rare occurrences where the gamepad module just gets stuck for whatever reason.
Can you try to disable gamepad API in the ``Advanced Settings``?
![sHXTDrffEC](https://user-images.githubusercontent.com/22834512/182045334-0f6c7a24-3c6a-462e-a353-2db2c455a549.png)
 
If that doesnt work, try disabling the "Motion Controller" Game-Controller HID device in the 'Device Manager' or 'Devices and Printers' (Or other related HID devices). This seem to work for some people. Still not sure why this is causing it. Im unable to reproduce this issue nor do i have candidates for testing builds.

**Comment by CannedToes** [comment]
Hello again,
Thank you! Disabling the gamepad API worked for me, I can now access everything and pair my controllers, 
Thank you again for your awesome support, I wish you good luck with your project friend!
