### ISSUE TITLE
Unable to connect PS Move controllers

### ISSUE THREAD

**Issue by b0mbays** [Timocop/PSMoveServiceEx#14]
Hi, I have tried many times to connect but i'm getting the same errors each time.

I'll paste them below, any help is greatly appreciated!

<img width="813" alt="error2" src="https://user-images.githubusercontent.com/55556007/183215989-26c748fd-5e8c-48df-918e-e9e7ef65ac30.PNG">
<img width="966" alt="error1" src="https://user-images.githubusercontent.com/55556007/183215994-1ccf99de-5b37-4424-8e2f-10add28a67b8.PNG">

**Comment by Timocop** [comment]
Lets start with the hardware you are using.
HMD? Controllers? BT Adapter?

And take a look at this aswell [Bluetooth-Requirements](https://github.com/Timocop/PSMoveServiceEx/wiki/B.-Hardware-Requirements#%EF%B8%8F-bluetooth-requirements).

**Comment by Timocop** [comment]
Closed due to bad Bluetooth Adapter.
