### ISSUE TITLE
disable magnetometer?

### ISSUE THREAD

**Issue by ghost** [Timocop/PSMoveServiceEx#15]
There is a lot of magnetic interference in my room that makes the magnetometer do more harm than good, is there any way to disable it and just run off the accelerometer and gyro?

**Comment by Timocop** [comment]
How do you calibrate your PSmove controller?
There are some tips and ticks:
 - Calibrate the magnetometer away from any surface (metallic, fabric, electric devices etc.) Optimal would be in the middle of the playspace.
 - Switch between ``Last Square`` and ``Bounds`` in magnetometer calibration. See whats better. ``Bounds`` might be a little inaccurate but its more compatible.
 - Adjust bad drift using ``Magnetometer Center (Yaw)`` setting.
 - Calibrate in a different room.
 - Use external IMU (SlimeVR or owoTrackVR).

If you want to disable magnetometer there is currently no option. You can go in the controller *.json and zero out all magnetometer values. Or you switch to ``MadgwickARG" (Which enables only gyro) But its currently also very bugged.
