### ISSUE TITLE
How to use webcams and not ps3 eyes?

### ISSUE THREAD

**Issue by gozzie01** [Timocop/PSMoveServiceEx#16]
The ReadMe suggests that you can use webcams and not ps3 eyes how do i configure this as it does not appear to be working off the bat with my setup.

**Comment by Timocop** [comment]
You have to use the [PSMoveServiceEx Virtual Device Manager](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager). Dont forget to do lens calibration when you use Webcams since PS-Eyes have recalculated lens calibration.

**Comment by gozzie01** [comment]
That's worked  thanks

**Comment by Timocop** [comment]
Just make sure you calibrate webcams lens with chessboard pattern paper using PSMoveServiceEx to get rid of any fish eye effect.
