### ISSUE TITLE
how to solve this calibration problem?

### ISSUE THREAD

**Issue by lotsarfati** [Timocop/PSMoveServiceEx#17]
![image](https://user-images.githubusercontent.com/116073900/198269000-e04d8967-df7d-4c9f-a00b-5caf884028ce.png)

from top to bottom you can see what happens in real life compers to what the computer see. so when they are opposite to one another they have huge distance but when the lights touching each other it works fine .
this problem is making all kind of wierd bugs because they move not at the same way in space .
they are in the same calibration place, anywhere in the room i get the same result. there is any way to calibrate them in the same space? it looks like they move the same way unequally in my room.

i have another problem which i think that it is because of this one . when i sit and use kinnect to vr it align perfectly but when i stand up it suddenly stop being align and they are in unrealistic distance from one another

**Comment by Timocop** [comment]
This isnt a problem, its just the PSMS PSmove preview model having a little offset. This has no effect on tracking.

If you are using K2EX driver, make sure you manually calibrate correctly. If you have scaling problems, use different calibration mat methods or use controller scaling offsets in ``Controller Settings``.

**Comment by Timocop** [comment]
Also in K2VR avoid Roll/Pitch rotation when calibrating. Restart calibration if you accidently Roll/Pitch your playspace. Only move your playspace in XYZ and rotate in Yaw you dont need to do anything else.

**Comment by lotsarfati** [comment]
> This isnt a problem, its just the PSMS PSmove preview model having a little offset. This has no effect on tracking.
> 
> If you are using K2EX driver, make sure you manually calibrate correctly. If you have scaling problems, use different calibration mat methods or use controller scaling offsets in `Controller Settings`.

when i am sitting i can clibrate on k2vr but when i am standing they change their place. 
also i tried to calibrate with 4 calibration papers and i had problem with it because when i print them they are not 100% the side of the paper. if i choose do print them at the size of the paper then it doesnt print them accurate enough. do you have any solution to it?

**Comment by Timocop** [comment]
The print doesnt need to be pixel perfect. The print is just an indicator to help you where to place them. Dont put the controller the print itself, put it on the paper **corners** and **center**. You can even do it without anything being printed on it if you know the steps good enough.

Also i recommend moving around while calibrating playspaces not just standing still.

**Comment by Timocop** [comment]
In the upcoming version, v1.17 PSMS will have its own manual playspace calibrator. Please do not use K2VR/K2EX, Amethyst nor D4VR playspace calibration since they are very broken with PSMS for some reason.

![PSMoveConfigTool_B8lptEstEN](https://user-images.githubusercontent.com/22834512/199202803-8f6a3f01-9d5c-4b3b-b691-4a7f4720d563.png)

Also for better tracking quality, make sure you mount the cameras correctly. Mount them permanently without using tape! Because tape is not permanent and will sag over time. Also, the cameras should look down like 25-35° to the center of your playspace to get more uniform scaling because of minimal lens distortion. Place the cameras around you uniformly. Like, dont have 4 cameras in the front and 2 at the back. Always place them in a circle around you.

Example:
![PSMoveConfigTool_JLzYG4Szu2](https://user-images.githubusercontent.com/22834512/199203995-57d025c5-7985-485d-9e3c-dd4ef7e8d71f.png)

**Comment by lotsarfati** [comment]
> In the upcoming version, v1.17 PSMS will have its own manual playspace calibrator. Please do not use K2VR/K2EX, Amethyst nor D4VR playspace calibration since they are very broken with PSMS for some reason.
> 
> ![PSMoveConfigTool_B8lptEstEN](https://user-images.githubusercontent.com/22834512/199202803-8f6a3f01-9d5c-4b3b-b691-4a7f4720d563.png)
> 
> Also for better tracking quality, make sure you mount the cameras correctly. Mount them permanently without using tape! Because tape is not permanent and will sag over time. Also, the cameras should look down like 25-35° to the center of your playspace to get more uniform scaling because of minimal lens distortion. Place the cameras around you uniformly. Like, dont have 4 cameras in the front and 2 at the back. Always place them in a circle around you.
> 
> Example: ![PSMoveConfigTool_JLzYG4Szu2](https://user-images.githubusercontent.com/22834512/199203995-57d025c5-7985-485d-9e3c-dd4ef7e8d71f.png)

what are you using instead of k2vr?

**Comment by Timocop** [comment]
Just a notice: You can now use PSMS-EX Virtual Device Manager for SteamVR integration. Which is recommended.
https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager
