### ISSUE TITLE
PSMove Config Tool crashes after cursor leaves window at manual color selection

### ISSUE THREAD

**Issue by BowlFirst** [Timocop/PSMoveServiceEx#18]
Video: https://we.tl/t-lWs1BmvlLg

**Comment by Timocop** [comment]
Can you try this and see if it fixes the issue?

[PSMoveConfigTool.zip](https://github.com/Timocop/PSMoveServiceEx/files/9904744/PSMoveConfigTool.zip)

**Comment by BowlFirst** [comment]
Now opening the tracker settings just throws a message "Waiting for server response..."
Was done on a different computer with a fresh install of Windows to confirm this is not just my PC.
Video: https://we.tl/t-yeqEtzC9tC

**Comment by Timocop** [comment]
Sorry, forgot, you need the updated PSMS too, try these
[__DEV.zip](https://github.com/Timocop/PSMoveServiceEx/files/9908332/__DEV.zip)

**Comment by BowlFirst** [comment]
That fixed it. Thanks for your work on this project 👍
