### ISSUE TITLE
(FEATURE REQUEST) Background/Tray utility

### ISSUE THREAD

**Issue by StrataWare3376** [Timocop/PSMoveServiceEx#22]
I'm so estatic to see the project impvoved upon and picked up! I'm looking to use an external application for bulb tracking, and want to be able to boot this service/utility in the background allowing me to have light and button inputs without piping through an third service (freepie).

Would it be possible to get a "bulb on" or background feature? even a applet in the testing folder, anything would bring me joy! thanks!

**Comment by Timocop** [comment]
If you want to control controllers *(e.g. turn on bulb and read button inputs)* I suggest using the new .NET PSMS-EX CAPI for your program.
https://github.com/Timocop/PSMoveServiceEx-CAPI.NET

It's very easy to use, here is an example: 
https://github.com/Timocop/PSMoveServiceEx-CAPI.NET/blob/master/PSMS_CAPI_Test/Module1.vb

**.NET CAPI is still WIP, there will be a lot of changes!**
I hope this helps.

**Comment by Timocop** [comment]
Did this help you? If yes, i will close this.
