### ISSUE TITLE
SharpShooter button support

### ISSUE THREAD

**Issue by StrataWare3376** [Timocop/PSMoveServiceEx#25]
I have a PS move SharpShooter and a couple buttons work properly, but most either conflict or simply do not work. I'm hoping this will receive proper support as it is great for lightgun/vr applications. Thank you!

**Comment by Timocop** [comment]
New major devices will not be implemented until i remake PSMoveService in .NET which allows me to speedup development because my C++ knowledge is limited and slowed down because of it.
I hope you can wait until then! Thank you!
