### ISSUE TITLE
controller disappears after all the pseyes can't see them 

### ISSUE THREAD

**Issue by omran3214** [Timocop/PSMoveServiceEx#28]
I came across a weird bug 
I have two cameras and two controllers and everytime i run PSMS and check the tracking pose for each controller one of them will disappear whenever i cover the light bulb with my hand and it doesn't reappear when i let go. And everytime i restart the PSMS it only happens to one of the controller randomly.
How can i fix it? Should I use the previous versions?

**Comment by Timocop** [comment]
Check for color collisions in Color Calibration. Blacklist areas such as windows, monitors and led strips that may get picked up by the cameras. Check "Show color collisions" and see.
