### ISSUE TITLE
Virtual HMD Doesn't track in 6DoF

### ISSUE THREAD

**Issue by SanyaMine** [Timocop/PSMoveServiceEx#3]
It simply doesn't track after the update, but it can see the colors
Steps to reproduce - create Virtual HMD in 0.13 and try to update PSMoveServiceEx to version 0.14

**Comment by Timocop** [comment]
Will be investigated, thank you!

**Comment by Timocop** [comment]
Fixed in 56b099b1a729bc4c7cb422c29f1bc17f0dc44c02
