### ISSUE TITLE
tracker unavailable

### ISSUE THREAD

**Issue by gaming11102006** [Timocop/PSMoveServiceEx#32]
my pseye camera is working but tracker setting not available , [like that PICTURE](https://imgur.com/a/0iwcEg4)
as a solution?
I am very very novice, thanks
edit: yes, I'm a novice, you know you can read

can you link image? You know I'm very novice again

**Comment by Timocop** [comment]
Are you using PSMoveServiceEx remotely on a different computer?

**Comment by gaming11102006** [comment]
I think so, it was my first ps3 eye

**Comment by Timocop** [comment]
Calibration and Video previews being unavailable means you are connecting to PSMoveServiceEx remotely. What ``IP:PORT`` are you connecting to with Config Tool?

**Comment by gaming11102006** [comment]
I don't know the IP port, do you know where the ip port is?

**Comment by Timocop** [comment]
When you start PSMSX Config Tool, what IP does it display?
The default IP is local for a local connection to PSMoveServiceEx is ``127.0.0.1`` or ``localhost``.

**Comment by gaming11102006** [comment]
https://imgur.com/a/OTCKzC7

**Comment by Timocop** [comment]
Use ``127.0.0.1`` and try again.

**Comment by gaming11102006** [comment]
It doesn't work, I have the ipv4 number as it was 192.0.0.0 (private and like server address), and what about "server port"?

**Comment by Timocop** [comment]
192.0.0.0 is a LAN address, use 127.0.0.1. Dont use PSMoveServiceEx over the Local Area Network for calibration.
They need to be on the **same computer**.
If you cant use 127.0.0.1 nor localhost then you misconfigured your Windows settings (or whatever settings there is).

**Comment by Timocop** [comment]
Actually ``localhost`` should be used not 127.0.0.1, PSMSX only has a check for that but not for 127.0.0.1.

**Comment by gaming11102006** [comment]
oh, okay but i mean what about "server port"?

**Comment by Timocop** [comment]
What about it? Just leave everything default and click "Connect"

**Comment by gaming11102006** [comment]
well, i tried but that doesn't work

**Comment by Timocop** [comment]
What language is your operating system?

**Comment by gaming11102006** [comment]
spanish and tracker setting is already available, thank you very much

**Comment by gaming11102006** [comment]
you can close if you want

**Comment by Timocop** [comment]
How did you fix your problem?
