### ISSUE TITLE
Virtual Cameras saying they are not connected even though they are setup via Virtual Device Manager

### ISSUE THREAD

**Issue by FireStudioYT** [Timocop/PSMoveServiceEx#35]
The title says it all

**Comment by Timocop** [comment]
If you are using PSMoveServiceEx and Virtual Device Manager, make sure both programs are not elevated and dont run with higher permissions. Run both programs normally.

**Comment by FireStudioYT** [comment]
> If you are using PSMoveServiceEx and Virtual Device Manager, make sure both programs are not elevated and dont run with higher permissions. Run both programs normally.

nope still the same problem
![image](https://github.com/Timocop/PSMoveServiceEx/assets/85067873/182718cf-9744-4504-a1e4-aa0c3c2b8f79)

**Comment by Timocop** [comment]
Can you show me the "Virtual Trackers" section in VDM?

**Comment by FireStudioYT** [comment]
> Can you show me the "Virtual Trackers" section in VDM?

![image](https://github.com/Timocop/PSMoveServiceEx/assets/85067873/6415c7e1-1c1e-4827-b23f-1f9bea90782c)

**Comment by Timocop** [comment]
Show the "Tracker Properties" too

**Comment by FireStudioYT** [comment]
> Show the "Tracker Properties" too

![image](https://github.com/Timocop/PSMoveServiceEx/assets/85067873/33eab2a7-a6f9-45bd-9be3-8071caad7c26)
Its because of the id isnt it? i didnt realize it was a button

**Comment by Timocop** [comment]
Yes, you have to set the tracker ids then it will work. If you have 2 virtual trackers enabled in PSMS-EX, then you have to set them to 0 and 1 corresponding to the tracker id in PSMS-EX.

**Comment by FireStudioYT** [comment]
> Yes, you have to set the tracker ids then it will work. If you have 2 virtual trackers enabled in PSMS-EX, then you have to set them to 0 and 1 corresponding to the tracker id in PSMS-EX.

Thanks man youve been a real help

**Comment by Timocop** [comment]
No problem, always here to help. You can join our PSMS-EX discord server if you want for faster support and announcements.

**Comment by FireStudioYT** [comment]
> No problem, always here to help. You can join our PSMS-EX discord server if you want for faster support and announcements.

can you send me a invite the one on github doesnt work

**Comment by Timocop** [comment]
The link does not work?

https://discord.gg/CXPnUanhZT

**Comment by FireStudioYT** [comment]
> The link does not work?
> 
> https://discord.gg/CXPnUanhZT

nope

**Comment by FireStudioYT** [comment]
> The link does not work?
> 
> https://discord.gg/CXPnUanhZT

nope
![brave_cZaFm4clkl](https://github.com/Timocop/PSMoveServiceEx/assets/85067873/be645fd4-d959-492b-b94b-05da87fbff5e)

**Comment by Timocop** [comment]
Seems more like a Discord issue on your end because i can use the invite link in a private-browser tab and even use it without an account and discord client. Other people also have used this link 13 times.
Copy the link into your Discord client maybe that works.

**Comment by FireStudioYT** [comment]
> Seems more like a Discord issue on your end because i can use the invite link in a private-browser tab and even use it without an account and discord client. Other people also have used this link 13 times. Copy the link into your Discord client maybe that works.

thanks im in
