### ISSUE TITLE
Is there FreePIE Support

### ISSUE THREAD

**Issue by wohdek21** [Timocop/PSMoveServiceEx#36]
Hello, i'm wanted to know is there FreePIE bridge?

**Comment by Timocop** [comment]
Yes/No, you have to use the legacy PSMoveService FreePIE bridge. But you dont need it anymore since the VDM SteamVR overrides.

**Comment by wohdek21** [comment]
ok thx

**Comment by andont** [comment]
> Yes/No, you have to use the legacy PSMoveService FreePIE bridge. But you dont need it anymore since the VDM SteamVR overrides.

I have the following setup:

1. VDM is used to manage PSMoveServiceEx (install, restart, config etc.)
2. PSMoveService FreePIE bridge
3. FreePIE with example mouse script from the bridge

I am able to use PS Move as a mouse which is my goal (to use it as a light gun for example) with only gyro and without any camera. Is it possible to do so only with VDM and what are the steps? 

PS. Any plans for virtual XInput device for PS Move (so it can be used as controller)?

Thank you.
