### ISSUE TITLE
How to output as freetrack?

### ISSUE THREAD

**Issue by slayermaster** [Timocop/PSMoveServiceEx#40]
Instead of iVRy, I'm using VRidge because it has it's own reprojection system so it's much smoother. But VRidge only supports Freetrack for its tracking.

**Comment by Timocop** [comment]
There is not updated FreePIE for PSMoveServiceEx yet. So you have two choices:
- Use the **legacy PSMoveService FreePIE** software, to translate PSMoveServiceEx sensor and optical data and send it to VRidge.
- Use **PSMoveServiceEx Virtual Device Manager** and its **SteamVR Tracker Overrides** feature to redirect your original VRidge HMD pose and replace it with PSMS-EX pose data.

**Comment by Timocop** [comment]
Did this answer your question?
