### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by LuckyTheCookie** [Timocop/PSMoveServiceEx#43]
Hello, I have a display bug on my PC but I don't know why 😅
![image](https://github.com/user-attachments/assets/2f6feb89-2032-4227-bbee-a99661b4ace6)
The buttons work but it's very problematic because I don't really know what I'm doing 
The image displays black and green bands that "sizzle" : 

- I have tried to restart my PC.

- My PC is up to date

- My graphics drivers are up to date (Nvidia Geforce RTX3060 - v560.70
![image](https://github.com/user-attachments/assets/eb853c98-ab8e-4fcd-bd95-85372c777002)

- I've tried reinstalling the program...
But it doesn't change anything 

My PC is running Windows 11 23H2 - Build 22631.3880
![image](https://github.com/user-attachments/assets/59506f0a-661a-41b7-9926-ca22caccf0b5)

Do you know what I can do?
Thank you in advance for reading my problem :)

**Comment by LuckyTheCookie** [comment]
If your program requires special libraries, here's what's installed on my PC
I'm sorry, I know it's a lot :o 

![image](https://github.com/user-attachments/assets/c6c0e4cb-3cb2-4703-8dab-434482a12d18)
![image](https://github.com/user-attachments/assets/8294b8de-8b59-44ad-a9a5-63c36b97981a)
![image](https://github.com/user-attachments/assets/072e3430-3e2d-4423-9e48-6beedd12cce2)

**Comment by Timocop** [comment]
You are using Intel Integrated Graphics to render the Config Tool, which is a common issues for OpenGL apps like this on Laptops.

You have two options:
- Disable Intel Integrated Graphics using Windows Device Manager. **(Recommended for Desktops)**
- Set the Config Tool GPU to Nvidia using ``Windows Settings > System > Display > Graphics Settings`` select ``Classic App`` then select the config tool application and then your Nvidia GPU. **(Recommended for Mobile devices)**

![image](https://github.com/user-attachments/assets/7f8ce480-6e98-48b1-9252-33dd4a59f901)

**Comment by LuckyTheCookie** [comment]
Thank you very much for your very quick reply!
It's working properly now :)
