### ISSUE TITLE
[feature request] ability to track slimevr tracker if they include an RGB led for identification.

### ISSUE THREAD

**Issue by tails101** [Timocop/PSMoveServiceEx#44]
It would be nice to track a slime VR tracker if it include a RGB led for identification.

Or a phone with the owotracker app (compatible with slime tracker)
With the screen showing an identifiable color for tracking.

I think this will replace psmove trackers nicely and fix the drifting issue most of those device have.
I think this is interesting in the long run to add compatibility.

**Comment by Timocop** [comment]
SlimeVR/owoTrack/moveTrack with additional RGB bulb is already possible. Please consult the Wiki or Discord server (which is more active).
