### ISSUE TITLE
PSMS Freeze when connect psmove

### ISSUE THREAD

**Issue by anar4732** [Timocop/PSMoveServiceEx#7]
Hi, my issue is the same with this but there is no solution so I'm writing here. 
https://github.com/psmoveservice/PSMoveService/issues/673

It doesn't matter if I connect my PSMove with USB or Bluetooth.
when I start PSMS while my PSMove are connected the config tool couldn't connect the PSMS stucks at "connecting to PSMoveService".
if I start the PSMS before connecting the PSMove it freezes with the message on the ConfigTool "waiting for controller list response"

My PSMove Model: ZCM2U
The PSMS I Using: PSMoveServiceEx v0.15.2

PSMS Log if I start it while PSMove are connected:
https://pastebin.com/u7pPtQ4b

PSMS Log if I connect the PSMove after starting the PSMS:
https://pastebin.com/wdJNF56i

Thank you for anyone who trying to help 😊
and Thank you for the fork and expending the lifespan of PSMS ❤

**Comment by anar4732** [comment]
I tried to debug it (not ex version the old version) and it seems to hang on exactly this line `IDirectInputDevice8_Acquire(devicePrivate->deviceInterface);` on DeviceManager line 953

**Comment by anar4732** [comment]
Finally fixed it, if anybody else has this problem mine was caused by the ViGEmuBus driver I installed for DS4Windows.

**Comment by Timocop** [comment]
I've seen this issue on some users already where it would just freeze with "waiting for controller list response" if they attach more than one controller. I still need to investigate this further so ill reopen this issue for now. Thanks for investigating the issue as well!

**Comment by Timocop** [comment]
Can you confirm this also happening with "Enable gamepad API" turned off in the advanced settings?
![PSMoveConfigTool_DSwM1UZoDD](https://user-images.githubusercontent.com/22834512/171335272-4ba73279-63e6-4b37-a685-1e9cadfe424a.png)

**Comment by Timocop** [comment]
Just as reference: https://github.com/Jays2Kings/DS4Windows/issues/26

**Comment by AMD-Boii** [comment]
> Just as reference: [Jays2Kings/DS4Windows#26](https://github.com/Jays2Kings/DS4Windows/issues/26)

But that's an old version. There are actual program https://github.com/Ryochan7/DS4Windows/releases

**Comment by Timocop** [comment]
Seems like both are archived, so both are deprecated?
Anyways, I have updated PSMS-EX gamepad hot-plug detection and option to use XInput API only. PSmove controllers input will still work even with gamepad API disabled. Not sure about Navi controllers however. I have also added some additional logging as well.

**Comment by anar4732** [comment]
Hi. I installed ViGEmuBus again to test but everything works as normal now even with ViGEmuBus. IDK what changed. so weird.

**Comment by anar4732** [comment]
I confirm the same thing happens when "Enable gamepad API" are disabled. does this mean my debug is wrong?

**Comment by anar4732** [comment]
Removed HideHide (not ViGEmuBus) and it works again. maybe something with it.

**Comment by Timocop** [comment]
Can you post a screenshot of the PSMS output when it starts to hang?

**Comment by anar4732** [comment]
> Hi, my issue is the same with this but there is no solution so I'm writing here. [psmoveservice#673](https://github.com/psmoveservice/PSMoveService/issues/673)
> 
> It doesn't matter if I connect my PSMove with USB or Bluetooth. when I start PSMS while my PSMove are connected the config tool couldn't connect the PSMS stucks at "connecting to PSMoveService". if I start the PSMS before connecting the PSMove it freezes with the message on the ConfigTool "waiting for controller list response"
> 
> My PSMove Model: ZCM2U The PSMS I Using: PSMoveServiceEx v0.15.2
> 
> PSMS Log if I start it while PSMove are connected: https://pastebin.com/u7pPtQ4b
> 
> PSMS Log if I connect the PSMove after starting the PSMS: https://pastebin.com/wdJNF56i
> 
> Thank you for anyone who trying to help 😊 and Thank you for the fork and expending the lifespan of PSMS ❤

I did in my first post.

**Comment by Timocop** [comment]
I've updated PSMS to v0.15.3, can you get the newest release and try again?

**Comment by anar4732** [comment]
will do. 👍

**Comment by Timocop** [comment]
Any further issues on this or is this resolved?

**Comment by anar4732** [comment]
it's fixed for me but not sure from PSMS.

**Comment by uwuclara** [comment]
Having the same issue here. 
When I start PSMS with controller connect thru USB/Bluetooth it hangs on config like  [anar4732](https://github.com/anar4732) sent. 
When I start PSMS and connect AFTER it shows this with 0.15 ver https://prnt.sc/76qtS6ZntG9X
When I start PSMS and connect AFTER it shows this with newest ver https://prnt.sc/62IpphhnJZ3f
This is the same result even if bluetooth adapter is off/on or controller paired/unpaired

I'm lost here. I even got new bluetooth adapter. It works with my win11 machine that has celeron with integrated GPU, so I can't even use it. My host pc is newest version of win10.

**Comment by anar4732** [comment]
@uwuclara do you have DS4Windows or WiGEmuBus?

**Comment by uwuclara** [comment]
nope. But just disabled enable gamepad api and it works.

**Comment by Timocop** [comment]
Assume this issue does not occur anymore. Closed.
