### ISSUE TITLE
DSU protocol support for Dolphin

### ISSUE THREAD

**Issue by otto500206** [Timocop/PSMoveServiceEx#9]
Dolphin, a Wii emulator, uses [DSU protocol](https://wiki.dolphin-emu.org/index.php?title=DSU_Client) for getting motion and input from compatible applications. This, can be used for motion capabilities of input devices on Dolphin. 

The original PSMoveService isn't compatible with this protocol, so we can't use PS Move controllers on Dolphin using it. But also, there are no other way for PS Move which uses DSU protocol. If I know right, PCMoveService can get all information from a PS Move which Dolphin can get from a Wiimote. This means that if implemented, the only problem left would be the button setup. However, if it also supports the Navigation Controller, this can be solved. 

If it's possible, can DSU protocol please be added to PSMoveServiceEx?

**Comment by Timocop** [comment]
As far as i understand, DSU only supports 3DoF motion input am i correct? 
PSMoveService might be a bit too overkill for this purpose then. I think its better to switch to PSMoveAPI instead which is more lightweight and is exactly made for that purpose. It supports all controllers that PSMoveService supports.

**Comment by otto500206** [comment]
I know PSMoveService might be bit too overkill, but PSMoveAPI is harder to install, so it might be hard for some people to use. And, DSU would still need to be implemented, there is no info about it being implemented on PSMoveAPI, especially in it's Github repo(it doesn't even haves a question about it).

**Comment by Timocop** [comment]
The DSU protocol will not be natively implemented into PSMS-EX because it already uses its own protocol. 
Feel free to create an extension for PSMS-EX that uses its protocol and translates into DSU instead.

**Comment by otto500206** [comment]
I don't think you understand what I wanted.

**Comment by Timocop** [comment]
What i understand from what you said is you want to use PSmove controllers (button input and gyro motion data) for other DSU supported apps like Dolphin?

**Comment by otto500206** [comment]
Exactly. They don't support any other protocol.

**Comment by PiporGames** [comment]
While DSU is an option for Dolphin, I think it also allows reading sensor data from the SDL API. Currently, when using either PSMoveAPI or PCMoveService the controller maps itself as a valid SDL input (strangely, it does as the last device possible).
If the PS4 controller sensor data can be read in Dolphin trough SDL, I'm guessing maybe cramming that data through the PSMove's SDL input will allow for Dolphin to read that.
The data being read is as follows:
![Image](https://github.com/user-attachments/assets/9ed4fe0d-cc14-445a-88b7-749d79961e70)
It stays static, without refreshing the values.
Making this work on Dolphin would open a lot of possibilities for the PSMove reusability and usage.
Thanks.
